#pragma kernel GetDensityMap
#include "Assets\Shaders\Compute\Includes\NoiseFunctions.compute"

RWTexture3D<float> densityMap;
int textureSize;
float3 chunkCoords;
float chunkSize;

float noiseScale;


float3 GetWorldSpaceOfPoint(int3 index) {
    return index + (chunkCoords * chunkSize);
}

[numthreads(8,8,8)]
void GetDensityMap(uint3 id : SV_DispatchThreadID) {
    densityMap[id] = snoise(GetWorldSpaceOfPoint(id) * noiseScale) + 0.5f;
}
